import{a as m,S as w,i as u}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const h of r.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&s(h)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();m.defaults.baseURL="https://pixabay.com/api/";const L={key:"42291336-b4c9ef387c9d7e209159058e7",image_type:"photo",orientation:"horizontal",safesearch:!0},g=async(o,t,i)=>{try{return(await m.get("?",{params:{q:o,...L,page:t,per_page:i}})).data}catch(s){throw s}},b=(o,t)=>{o.forEach(s=>{const e=`<li class="photo">
            <a href="${s.largeImageURL}" data-lightbox="photos">
                <img src="${s.webformatURL}" alt="${s.tags}" title="${s.tags}" class="img">
            </a>
            <ul class="list">
                <li class="item"><h2>Likes <span>${s.likes}</span></h2></li>
                <li class="item"><h2>Views <span>${s.views}</span></h2></li>
                <li class="item"><h2>Comments <span>${s.comments}</span></h2></li>
                <li class="item"><h2>Downloads <span>${s.downloads}</span></h2></li>
            </ul>
        </li>`;t.insertAdjacentHTML("beforeend",e)}),new w(".photos a",{}).refresh()},d=document.querySelector(".container ul"),n=document.querySelector(".loader"),f=document.querySelector(".form"),P=document.querySelector("input"),a=document.createElement("button");a.textContent="Load more";a.style.margin="0 auto";a.style.marginTop="15px";a.style.width="150px";n.after(a);a.style.display="none";let p="",l=1;const c=15;let y=1;f.addEventListener("submit",async o=>{if(o.preventDefault(),l=1,d.innerHTML="",p=P.value.trim(),!p)u.error({title:"Error",message:"Please enter a search term",position:"topRight"});else{n.style.display="block",a.style.display="none";try{const t=await g(p,l,c),i=t.totalHits;y=Math.ceil(i/c),i===0?u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",icon:""}):(b(t.hits,d),t.hits.length<c?a.style.display="none":a.style.display="block"),n.style.display="none"}catch(t){n.style.display="none",console.log(t)}}f.reset()});a.addEventListener("click",async()=>{n.style.display="block";try{l++;const o=await g(p,l,c);n.style.display="none",b(o.hits,d);const t=d.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*3,behavior:"smooth"});const i=o.totalHits;y=Math.ceil(i/c),l>=y&&(a.style.display="none",u.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch(o){n.style.display="none",console.log(o)}});
//# sourceMappingURL=commonHelpers.js.map
